# Generated by Django 4.0.5 on 2022-06-19 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_shortedurl_shortenedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_url',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='ShortenedUrlStatPerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(max_length=100)),
                ('number_of_clicks', models.IntegerField()),
                ('shortened_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shortenedurl')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
